CREATE TABLE dbo.ErrorLog (
	Id INT IDENTITY(1,1),
	Number INT NOT NULL,
	Severity INT NOT NULL,
	[State] INT NOT NULL,
	Prodecure VARCHAR(200) NOT NULL,
	Line INT NOT NULL,
	[Message] VARCHAR(8000) NOT NULL,
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);