CREATE TABLE dbo.PositionTypes (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Position VARCHAR(255) NOT NULL,
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT REFERENCES dbo.Employee(Id) DEFAULT NULL,
	UNIQUE (Position)
);
