CREATE TABLE dbo.ScheduleTester (
	Id INT IDENTITY(1,1) PRIMARY KEY,	
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	[Status] TINYINT DEFAULT 0,
	Note VARCHAR(2000) DEFAULT NULL,
	ModifedDate DATETIME DEFAULT NULL,
	EmployeeId  INT REFERENCES dbo.Employee(Id) NOT NULL,
	CreatedBy  INT REFERENCES dbo.Employee(Id) NOT NULL,
	ScheduleId  INT REFERENCES dbo.Scheduletest(Id) ON DELETE CASCADE NOT NULL
);