CREATE TYPE dbo.CandidateType AS TABLE
(
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	PhoneNumber VARCHAR(20) NOT NULL,
	Email VARCHAR(254) NOT NULL,
	[Address] VARCHAR(254) NOT NULL,
	CV VARCHAR(MAX) NOT NULL,
	PositionId INT NOT NULL,
	RoleId INT NOT NULL,
	StatusId INT NOT NULL,
	CreatedBy INT NOT NULL
);